language: scala
scala:
- 2.11.8
jdk: oraclejdk8
script:
- sbt compile
- sbt gatling:test
env:
  gh:
    pwd:
      secure: mU+FgeO1FWqizewCcIn/yXJPQ0TdxPL8CoF7f2htWu80VsnnjkOlJZvV4y4VJfbWAVSdku8RNtltx0yqk8GYwBh1DDajWL1o1QEhDWefn6tiQ7vVF1bqSdJNK5Enz8/kDHNU8xWnwKOST74m+3XhaN3Wx3aA3sgQl2C2jlCTqbFzk/fO2vvm5M4IB52wIta2IvbH/1MBFNQRBCTDh6M/J+BmRwwi0bkGwZ1OHT4a8SoPlSnjQjmrn0tQO8XanPHiWoaOjPy8GhXlIt096pxynFzleBajyRnn8DLHgXPpUQl7CWJiYnUi09DmYcPTNE3iZB1CrCT1freNhUto+bUriNXFFSD8wioF1Fx4z7aXRrn1WQF0ms3b1RAvEBy6c7xnMQHHbblALKu4wukD2BZOrEAOWCGgUXIpqRG+8L70vGK80gQ47RvV7aJG4387klCZD+R5NxhsHniymfr3Z2E1qrAcXCncD4xDG9cho7uZdWZ8wOsM+ci2wGTlnfd3zHeqmqQCKVxcLq/5GNgtwa1f6sySNtjoc7lv9qKfZIc0bnzqM5WG2/Hk0Lx2egR061MLNa4PWv5q4/1I9kWeyeV9JSskCt4o8Vxo01JkhjejCL15SBLlZH6FPqwB/+HuwA8gOH+CCo85Zs9ousFAt2TyBcCSMkpKz+l5g4z5RtJtfSw=
